version: 2

models:
  - name: int_trips_unioned
    description: >
      Union of green and yellow taxi data with normalized schema.

  - name: int_trips
    description: >
      Cleaned, enriched, and deduplicated trip data ready for marts.

    columns:
      - name: trip_id
        description: Unique surrogate key for each trip
        tests:
          - unique
          - not_null

      - name: vendor_id
        description: Taxi technology provider ID
        tests:
          - not_null

      - name: service_type
        description: Type of taxi service
        tests:
          - not_null
          - accepted_values:
              values: ['Green', 'Yellow']

      - name: pickup_datetime
        description: Timestamp when meter was engaged
        tests:
          - not_null

      - name: total_amount
        description: Total amount charged
        tests:
          - not_null

      - name: payment_type
        description: Payment method code

      - name: payment_type_description
        description: Human-readable payment method description