version: 2

models:
  - name: int_trips_unioned
    description: Union of green and yellow taxi trip data.

  - name: int_trips
    description: Cleaned, enriched, and deduplicated trips.
    columns:
      - name: trip_id
        description: Surrogate key.
        tests:
          - unique
          - not_null

      - name: vendor_id
        description: Taxi technology provider.
        tests:
          - not_null

      - name: service_type
        description: Taxi service type.
        tests:
          - not_null
          - accepted_values:
              values: ['Green', 'Yellow']

      - name: pickup_datetime
        description: Trip start time.
        tests:
          - not_null

      - name: dropoff_datetime
        tests:
          - not_null

      - name: total_amount
        description: Total fare charged.
        tests:
          - not_null