version: 2

models:
  - name: dim_zones
    description: Taxi zone dimension table

    columns:
      - name: location_id
        description: Unique zone identifier
        tests:
          - unique
          - not_null

      - name: borough
        description: NYC borough name

      - name: zone
        description: Zone name

      - name: service_zone
        description: Service zone classification


  - name: dim_vendors
    description: Taxi technology vendor dimension table

    columns:
      - name: vendor_id
        description: Unique vendor identifier
        tests:
          - unique
          - not_null

      - name: vendor_name
        description: Vendor company name


  - name: fct_trips
    description: Fact table containing all taxi trips

    config:
      contract:
        enforced: true

    columns:
      - name: trip_id
        description: Unique trip identifier
        data_type: string
        tests:
          - unique
          - not_null

      - name: vendor_id
        description: Taxi technology provider
        data_type: int64
        tests:
          - not_null
          - relationships:
              to: ref('dim_vendors')
              field: vendor_id

      - name: service_type
        description: Taxi service type
        data_type: string
        tests:
          - not_null
          - accepted_values:
              values: ['Green', 'Yellow']

      - name: pickup_location_id
        description: Pickup zone ID
        data_type: int64
        tests:
          - relationships:
              to: ref('dim_zones')
              field: location_id

      - name: dropoff_location_id
        description: Dropoff zone ID
        data_type: int64
        tests:
          - relationships:
              to: ref('dim_zones')
              field: location_id

      - name: pickup_datetime
        description: Trip start timestamp
        data_type: timestamp
        tests:
          - not_null

      - name: total_amount
        description: Total trip amount
        data_type: numeric
        tests:
          - not_null

      - name: payment_type
        description: Payment method code
        data_type: int64
        tests:
          - relationships:
              to: ref('payment_type_lookup')
              field: payment_type

      - name: payment_type_description
        description: Human-readable payment description
        data_type: string